// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:66178f88-a392-417e-90cb-6fa706ef3de7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_isUJEGuUy",
    "aws_user_pools_web_client_id": "ubpp0n1lk23rgadv0qb23eegq",
    "oauth": {
        "domain": "confirmation-local.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://unity-node-game-server.herokuapp.com/",
        "redirectSignOut": "https://unity-node-game-server.herokuapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
