// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:86736dd0-37e3-40b1-855c-74b662e25a2b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NMn2yeWJ4",
    "aws_user_pools_web_client_id": "58loi7nseg85g322jcphun0ql9",
    "oauth": {
        "domain": "unitynodeauth8acddaf0-8acddaf0-local.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
